### ISSUE TITLE
the process of register of backtrader community seems like broken

### ISSUE THREAD

**Issue by k0286** [mementum/backtrader.contrib#2]
Greeting,
Sorry for bothering you! @mementum   
Because I don't verify email, I can't post help message in the community forum.
And I don't find any other way can contact you.

I think the password recovery  and register process of community forum have some problems.

1. I can't use OAuth from github to login anymore. In my memory, I used to login with github' OAuth in a few months ago.
2. I try to recover my password, but the page from the password reset mail seems broken. It has no response after I click the reset password button.
3. I register a new account with other email address but don't  receive the confirm email even if I  try many times to verify my email. I've already checked the garbage mailbox B.T.W.

regards,

**Comment by sachin2c** [comment]
@mementum Looks like it's broken again. I get 504 Gateway Time-out after i accept the consent can you help ?

**Comment by chem-chikweze** [comment]
I could not open an account. It shows me the `504 Gateway Time-out` error.
